project:
  type: book
  output-dir: _book

book:
  title: "Introduction to Machine Learning and AI for Health Sciences"
  author: "Danilo Augusto Sarti"
  date: "2025-05-21"
  chapters:
    - index.qmd
    - introduction_AI.qmd
    - supervised_regression.qmd
    - three_methods.qmd
    - neural_networks.qmd
    - introd_bayesian.qmd
    - intro_missing.qmd
    - high_dims.qmd
    - clustering.qmd
    - references.qmd

website:
  site-url: "https://danilosarti.github.io/ai_health_book"
  repo-url: "https://github.com/danilosarti/ai_health_book"

bibliography:
  - references.bib

cite-method: citeproc
link-citations: true

format:
  html:
    theme:
      - cosmo
      - brand
